// Generated by Haxe 5.0.0-alpha.1
(function ($global) { "use strict";
var LowercaseTest = function() { };
LowercaseTest.myFunction = function(x) {
	return x * 2;
};
LowercaseTest.main = function() {
	var result = LowercaseTest.myFunction(5);
	console.log("LowercaseTest.zx:9:","Function result: " + result);
	var func = LowercaseTest.myFunction;
	var result2 = func(10);
	console.log("LowercaseTest.zx:14:","Function reference result: " + result2);
	console.log("LowercaseTest.zx:16:","Lowercase test completed!");
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
LowercaseTest.main();
})({});
