// Generated by Haxe 5.0.0-alpha.1
(function ($global) { "use strict";
Math.__name__ = "Math";
var Std = function() { };
Std.__name__ = "Std";
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var ZxSyntaxTest = function() {
	this.name = "ZxTest";
	this.age = 25;
	this.secret = "hidden";
};
ZxSyntaxTest.__name__ = "ZxSyntaxTest";
ZxSyntaxTest.getCount = function() {
	return ZxSyntaxTest.count;
};
ZxSyntaxTest.main = function() {
	var test = new ZxSyntaxTest();
	test.name = "Updated";
	test.age = 30;
	console.log("ZxSyntaxTest.zx:50:","Name: " + test.getName());
	console.log("ZxSyntaxTest.zx:51:","Age: " + test.getAge());
	ZxSyntaxTest.count = 42;
	console.log("ZxSyntaxTest.zx:55:","Count: " + ZxSyntaxTest.getCount());
	var result = test.processData(["a","b"],function(s) {
		console.log("ZxSyntaxTest.zx:58:","Processing: " + s);
	});
	console.log("ZxSyntaxTest.zx:59:","Result: " + Std.string(result));
	console.log("ZxSyntaxTest.zx:61:","ZX syntax test completed successfully!");
};
ZxSyntaxTest.prototype = {
	getName: function() {
		return this.name;
	}
	,getAge: function() {
		return this.age;
	}
	,getSecret: function() {
		return this.secret;
	}
	,processData: function(data,callback) {
		var result = [];
		var _g = 0;
		var _g1 = data.length;
		while(_g < _g1) {
			var i = _g++;
			result.push(i);
			callback(data[i]);
		}
		return result;
	}
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = "haxe.iterators.ArrayIterator";
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = "js.Boot";
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
String.__name__ = "String";
Array.__name__ = "Array";
js_Boot.__toStr = ({ }).toString;
ZxSyntaxTest.main();
})({});
